# steps:
# - label: "🔧 Test changed flaghh"
#   command: echo "sleep 360"
#   if_changed: src/**.

#
steps:
- label: "📄 Run regardless"
  command: |
    echo "hi"
    buildkite-agent annotate "Your annotation text here" --context $BUILDKITE_JOB_ID

- label: ":bash: Multiple Failure Points"
  command: |
    echo "Starting tests..."
    echo "$BUILDKITE_PLUGINS_PATH"
    
    # This will fail - missing dependency
    npm test
    
    # This will also fail - docker not running
    docker ps
    
    # This would fail too - file doesn't exist
    cat /nonexistent/file.txt
    
    echo "If you see this, something went wrong with our intentional failures"
  plugins:
  - AthreyaRay/chatgpt-logs
