# steps:
# - label: "🔧 Test changed flaghh"
#   command: echo "sleep 360"
#   if_changed: src/**.

#
steps:
- label: "📄 Run regardless"
  command: |
    echo "hi"
    buildkite-agent annotate "Your annotation text here" --job "$BUILDKITE_JOB_ID"

- label: ":bash: Run Something Faulty"
  command: |
    echo "$BUILDKITE_PLUGINS_PATH"
    docker ps
    echo "above command would fail as I stopped my docker"
  plugins:
  - AthreyaRay/chatgpt-logs
