steps:
- label: "🔧 Test changed flaghh"
  command: sleep 360
  if_changed: src/**.

- label: "📄 Run regardless"
  command: sleep 120

- label: ":bash: Run Something Faily"
  command: |
    echo "This will fail"
    exit 1
  plugins:
  - AthreyaRay/chatgpt-log-buildkite-plugin
