steps:
# - label: "🔧 Test changed flaghh"
#   command: echo "sleep 360"
#   if_changed: src/**.

# - label: "📄 Run regardless"
#   command: echo "hi"

- label: ":bash: Run Something Faily"
  command: |
    echo "$BUILDKITE_PLUGINS_PATH"
    docker ps 
    echo 'above command would fail as I stopped my docker'
  plugins:
  - AthreyaRay/chatgpt-logs
