steps:
# - label: "🔧 Test changed flaghh"
#   command: echo "sleep 360"
#   if_changed: src/**.

# - label: "📄 Run regardless"
#   command: echo "hi"

- label: ":bash: Run Something Faily"
  command: |
    echo "This will fail"
    exit 1
  plugins:
  - AthreyaRay/chatgpt-log#v1.0.0
